# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{formtastic_cocoon}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Van der Auwera"]
  s.date = %q{2011-02-09}
  s.description = %q{Unobtrusive nested forms handling in formtastic, using jQuery. Use this and discover cocoon-heaven.}
  s.email = %q{nathan@dixis.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "formtastic-cocoon.gemspec",
     "formtastic_cocoon.gemspec",
     "lib/formtastic_cocoon.rb",
     "lib/formtastic_cocoon/view_helpers.rb",
     "lib/generators/formtastic_cocoon/install/install_generator.rb",
     "lib/generators/formtastic_cocoon/install/templates/formtastic_cocoon.js",
     "spec/formtastic-cocoon_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nathanvda/formtastic_cocoon}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{gem that enables easier nested forms with formtastic}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/formtastic-cocoon_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

